const menuData ={
   "categories": [
    {"id": "noodle", "name": "特色重庆小面系列", "enName": "SpecialNoodle"},
    {"id": "RiceCombo", "name": "特色套饭", "enName": "RiceCombo"},
    {"id": "jfc", "name": "特色江湖菜", "enName": "SpecialStirFriesDishes"},
    {"id": "jcc", "name": "家常菜", "enName": "DailyCuisine"},
    {"id": "sv", "name": "特色炒菜", "enName": "Stir-fries Vegetable"},
    {"id": "Soup", "name": "特色汤类", "enName": "Soup"},
    {"id": "cd", "name": "特色凉菜", "enName": "Cold dish"},
    {"id": "side", "name": "特色小吃", "enName": "Side dish"},
    {"id": "fh", "name": "冒菜小火锅", "enName": "Fast hotpot"},
    {"id": "yl", "name": "饮料", "enName": "Drinks"}
  ],
    "items":[
    {
        "categoryId":"noodle",
        "name":"重庆小 面\/酸辣粉\/米线  ",
        "enName":"Chongqing Noodle\/Spicy Potato noodle\/Rice Noodle",
        "price1":8.99,
        "size1":"Medium ",
        "price2":10.99,
        "size2":" Large",
        "image":"./pic/res_project/m/xm.jpg",
        "desc1":"",
        "desc2":" Spicy level:spicy or not "
    },
    {
        "categoryId":"noodle",
        "name":"特色大排汤面",
        "enName":"Noodle with Pork Steak",
        "price1":" ",
        "size1":" ",
        "price2":14.99,
        "size2":" ",
        "image":"./pic/res_project/m/dpm.jpg",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"noodle",
        "name":"炸酱 面\/酸辣粉\/米线 ",
        "enName":"Ground Pork Sauce Noodle\/Spicy Potato noodle\/Rice Noodle",
        "price1":11.99,
        "size1":"Medium ",
        "price2":13.99,
        "size2":" Large",
        "image":"./pic/res_project/m/zj.jpg",
        "desc1":"",
        "desc2":"Spicy level:Spicy or not "
    },
    {
        "categoryId":"noodle",
        "name":"豌豆杂酱 面\/酸辣粉\/米线",
        "enName":"Ground Pork&Pea Sauce Noodle\/Spicy Potato noodle\/Rice Noodle",
        "price1":11.99,
        "size1":"Medium ",
        "price2":13.99,
        "size2":" Large",
        "image":"./pic/res_project/m/wdzjm.jpg",
        "desc1":"",
        "desc2":" Spicy level:spicy or not "
    },
    {
        "categoryId":"noodle",
        "name":"泡椒鸡杂 面\/酸辣粉\/米线",
        "enName":"Chichken Gizzards Noodle Noodle\/Spicy Potato noodle\/Rice Noodle",
        "price1":12.99,
        "size1":"Medium ",
        "price2":14.99,
        "size2":" Large",
        "image":"./pic/res_project/m/jzm.jpg",
        "desc1":" ",
        "desc2":" Spicy level:spicy or not "
    },
    {
        "categoryId":"noodle",
        "name":"三杂 面\/酸辣粉\/米线",
        "enName":"Gizzard,ground meat and bean Noodle\/Spicy Potato noodle\/Rice Noodle",
        "price1":12.49,
        "size1":"Medium ",
        "price2":14.49,
        "size2":" Large",
        "image":"./pic/res_project/m/szm.jpg",
        "desc1":"",
        "desc2":" Spicy level:spicy or not "
    },
    {
        "categoryId":"noodle",
        "name":"重庆红烧肉 面\/酸辣粉\/米线",
        "enName":"Chongqing pork stew Noodle\/Spicy Potato noodle\/Rice Noodle",
        "price1":11.99,
        "size1":"Medium ",
        "price2":13.99,
        "size2":" Large",
        "image":"./pic/res_project/m/hsrm.jpg",
        "desc1":"",
        "desc2":" Spicy level:spicy or not "
    },
    {
        "categoryId":"noodle",
        "name":"重庆牛肉 面\/酸辣粉\/米线",
        "enName":"Chongqing beef  Noodle\/Spicy Potato noodle\/Rice Noodle",
        "price1":12.99,
        "size1":"Medium ",
        "price2":14.99,
        "size2":" Large",
        "image":"./pic/res_project/m/nrm.jpg",
        "desc1":" ",
        "desc2":" Spicy level:spicy or not "
    },
    {
        "categoryId":"noodle",
        "name":"重庆肥肠 面\/酸辣粉\/米线",
        "enName":"Chongqing Intestine  Noodle\/Spicy Potato noodle\/Rice Noodle",
        "price1":12.99,
        "size1":"Medium ",
        "price2":14.99,
        "size2":" Large",
        "image":"./pic/res_project/m/fcm.jpg",
        "desc1":"",
        "desc2":" Spicy level:spicy or not "
    },
    {
        "categoryId":"noodle",
        "name":"肥肠牛肉 面\/酸辣粉\/米线",
        "enName":"Intestine & beef Noodle\/Spicy Potato noodle\/Rice Noodle",
        "price1":12.99,
        "size1":"Medium ",
        "price2":14.99,
        "size2":" Large",
        "image":"./pic/res_project/m/fcnrm.jpg",
        "desc1":"",
        "desc2":" Spicy level:spicy or not "
    },
    {
        "categoryId":"noodle",
        "name":"番茄炸蛋",
        "enName":"Tomato Sauce Soup with fried egg",
        "price1":" ",
        "size1":" ",
        "price2":12.99,
        "size2":" ",
        "image":"./pic/res_project/m/fqzd.jpg",
        "desc1":"面\/米线    Noodle\/Spicy Potato noodle\/Rice Noodle",
        "desc2":" Spicy level:non-spicy "
    },
    {
        "categoryId":"noodle",
        "name":"抄手",
        "enName":"Chongqing Wonton",
        "price1":11.99,
        "size1":"Medium ",
        "price2":13.99,
        "size2":" Large",
        "image":"./pic/res_project/m/cs.jpg",
        "desc1":"Spicy Soup\/Chicken Soup",
        "desc2":" "
    },
    {
        "categoryId":"noodle",
        "name":"鸡丝麻酱拌面",
        "enName":"Cold Noodle with sesame paste and chicken",
        "price1":" ",
        "size1":" ",
        "price2":13.99,
        "size2":" ",
        "image":"./pic/res_project/m/jsmjbm.jpg",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"noodle",
        "name":"鲜椒鸡拌面",
        "enName":"Noodle with Fried Pepper Chicken",
        "price1":" ",
        "size1":" ",
        "price2":14.99,
        "size2":" ",
        "image":"./pic/res_project/m/xjjm.jpg",
        "desc1":" ",
        "desc2":"Spicy level:Spicy"
    },
    {
        "categoryId":"noodle",
        "name":"回锅肉拌面",
        "enName":"Noodle with Twice cooked Pork",
        "price1":" ",
        "size1":" ",
        "price2":14.99,
        "size2":" ",
        "image":"./pic/res_project/m/hgrbm.jpg",
        "desc1":" ",
        "desc2":"Spicy level:Spicy"
    },
    {
        "categoryId":"noodle",
        "name":"泡椒牛肉拌面",
        "enName":"Noodle with Pickled Pepper Sliced Beef",
        "price1":" ",
        "size1":" ",
        "price2":15.99,
        "size2":" ",
        "image":"./pic/res_project/m/pjnrbm.jpg",
        "desc1":" ",
        "desc2":"Spicy level:Spicy"
    },
    {
        "categoryId":"noodle",
        "name":"泡椒猪肝拌面",
        "enName":"Noodle with Pickled Pepper Pork liver",
        "price1":" ",
        "size1":" ",
        "price2":15.49,
        "size2":" ",
        "image":"./pic/res_project/m/pjzgbm.jpg",
        "desc1":" ",
        "desc2":"Spicy level:Spicy"
    },
    {
        "categoryId":"noodle",
        "name":"三脆拌面",
        "enName":"Noodle With Gizzard\/tube\/tripe",
        "price1":" ",
        "size1":" ",
        "price2":15.49,
        "size2":" ",
        "image":"./pic/res_project/m/scbm.jpg",
        "desc1":" ",
        "desc2":"Spicy level:Spicy"
    },
    {
        "categoryId":"noodle",
        "name":"泡椒腰花拌面",
        "enName":"Noodle with Pork Kidney with Pickled Chili",
        "price1":" ",
        "size1":" ",
        "price2":15.49,
        "size2":" ",
        "image":"./pic/res_project/m/pjyhbm.jpg",
        "desc1":" ",
        "desc2":"Spicy level:Spicy"
    },
    {
        "categoryId":"noodle",
        "name":"三鲜砂锅米线",
        "enName":"Big bone soup Rice noodle",
        "price1":" ",
        "size1":" ",
        "price2":13.99,
        "size2":" ",
        "image":"./pic/res_project/m/sxmx.png",
        "desc1":" ",
        "desc2":"Spicy level:non-spicy"
    },
    {
        "categoryId":"noodle",
        "name":"麻辣砂锅米线",
        "enName":"Spicy Soup Rice Noodle",
        "price1":" ",
        "size1":" ",
        "price2":13.99,
        "size2":" ",
        "image":"./pic/res_project/m/mlmx.png",
        "desc1":" ",
        "desc2":"Spicy level:Spicy"
    },
    {
        "categoryId":"noodle",
        "name":"泡椒肉丝米线",
        "enName":"Spicy Pickle Rice Noodle with sliced Meat",
        "price1":" ",
        "size1":" ",
        "price2":13.99,
        "size2":" ",
        "image":"./pic/res_project/m/scrsmx.jpg",
        "desc1":" ",
        "desc2":"Spicy level:Spicy"
    },
    {
        "categoryId":"congee",
        "name":"皮蛋瘦肉粥",
        "enName":"Century Egg & Pork Congee",
        "price1":9.99,
        "size1":"Medium ",
        "price2":15.99,
        "size2":" Large",
        "image":" ",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"congee",
        "name":"鱼片粥",
        "enName":"Fish Congee",
        "price1":12.99,
        "size1":"Medium ",
        "price2":18.99,
        "size2":" Large",
        "image":" ",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"congee",
        "name":"海鲜粥",
        "enName":"Seafood Congee",
        "price1":12.99,
        "size1":"Medium ",
        "price2":18.99,
        "size2":" Large",
        "image":" ",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"congee",
        "name":"润肺猪肝粥",
        "enName":"Congee with pork liver",
        "price1":10.99,
        "size1":"Medium ",
        "price2":16.99,
        "size2":" Large",
        "image":" ",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"congee",
        "name":"白粥",
        "enName":"Congee",
        "price1":4.99,
        "size1":"Medium ",
        "price2":8.99,
        "size2":" Large",
        "image":"https://images.unsplash.com/photo-1512621776951-a57141f2eefd?q=80&w=400",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"RiceCombo",
        "name":"口水鸡饭",
        "enName":"Cold Spicy Chicken Rice Combo",
        "price1":11.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/tf/ksjf.png",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"RiceCombo",
        "name":"葱油香酥鸡",
        "enName":"Crispy Chicken Rice Combo",
        "price1":12.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/tf/cyxsjf.jpg",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"RiceCombo",
        "name":"鲜椒鸡饭",
        "enName":"Chicken with Spicy Pickled Pepper",
        "price1":13.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/tf/xjjf.png",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"RiceCombo",
        "name":"葱油大排饭",
        "enName":"Crispy Pork Steak Rice Combo",
        "price1":13.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/tf/cydpf.png",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"RiceCombo",
        "name":"蒜泥白肉饭",
        "enName":"Garlic Spicy Pork Rice Combo",
        "price1":13.49,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/tf/snbrf.png",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"RiceCombo",
        "name":"重庆红烧肉饭",
        "enName":"Chongqing Pork Stew Rice Combo",
        "price1":12.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/tf/hsrf.png",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"RiceCombo",
        "name":"麻婆豆腐饭",
        "enName":"Mapo Tofu Over Rice",
        "price1":12.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/tf/mpdff.png",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"RiceCombo",
        "name":"糖醋里脊饭",
        "enName":"Sweat and Sour Pork Rice Combo",
        "price1":12.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/tf/tcljf.png",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"RiceCombo",
        "name":"番茄鸡蛋饭",
        "enName":"Tomato scrambled eggs Over Rice",
        "price1":11.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/tf/fqjdf.png",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"RiceCombo",
        "name":"土豆肉丝饭",
        "enName":"Potato Pork Over Rice",
        "price1":12.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/tf/tdrsf.png",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"RiceCombo",
        "name":"青椒肉丝饭",
        "enName":"Green Pepper Pork Over Rice",
        "price1":13.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/tf/qjrsf.png",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"RiceCombo",
        "name":"泡椒肉丝饭",
        "enName":"Spicy Pickle Pork Over Rice",
        "price1":13.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/tf/pjrsf.png",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"RiceCombo",
        "name":"鱼香肉丝饭",
        "enName":"Fish-Flavored Pork Over Rice",
        "price1":13.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/tf/yxrsf.png",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"RiceCombo",
        "name":"回锅肉饭",
        "enName":"Twice Cooked Meat with Over Rice",
        "price1":13.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/tf/hgrf.png",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"RiceCombo",
        "name":"宫爆鸡丁饭",
        "enName":"Kung Pao Chicken Over Rice",
        "price1":13.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/tf/gbjdf.png",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"RiceCombo",
        "name":"葱爆牛肉饭",
        "enName":"Beef Stir-Fry with Scallions Rice Combo",
        "price1":14.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/tf/cbnrf.jpg",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"RiceCombo",
        "name":"香干小炒肉饭",
        "enName":"Pork with Green Pepper and Black Bean Sauce Over Rice",
        "price1":13.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/tf/xgxcrf.png",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"RiceCombo",
        "name":"水煮肉片饭",
        "enName":"Spicy Hot Pot Meat Rice Combo ",
        "price1":14.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/tf/szrpf.png",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"RiceCombo",
        "name":"滑蛋鸡肉\/牛肉\/虾饭",
        "enName":"Scrambled egg with chicken\/beef\/shrimp Over Rice",
        "price1":14.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/tf/hdf.png",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"RiceCombo",
        "name":"单人冒菜饭",
        "enName":"Small Hot Pot Rice Combo",
        "price1":14.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/tf/drmcf.jpg",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"RiceCombo",
        "name":"蘑菇牛肉饭",
        "enName":"Beef with mushrooms Over Rice",
        "price1":14.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/tf/mgnrf.png",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"RiceCombo",
        "name":"扬州炒饭",
        "enName":"Fried Rice with Eggs, Smoked Pork, Shrimp and Vegetable",
        "price1":13.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/tf/yzcf.png",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"RiceCombo",
        "name":"水煮牛肉饭",
        "enName":"Spicy Hot Pot Beef Rice Combo",
        "price1":15.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/tf/szrpf.png",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"RiceCombo",
        "name":"牛肉炒饭",
        "enName":"Fried Rice with Beef",
        "price1":13.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/tf/nrcf.png",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"RiceCombo",
        "name":"鸡杂炒饭",
        "enName":"Fried Rice with Gizzard",
        "price1":13.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/tf/jzcf.png",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"RiceCombo",
        "name":"炒牛肉河粉\/面",
        "enName":"Stir-fried Beef Rice Noodles\/Noodle",
        "price1":14.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/tf/nrchf.png",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"RiceCombo",
        "name":"蛋炒饭",
        "enName":"Fried Rice with Egg",
        "price1":11.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/tf/dcf.png",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"RiceCombo",
        "name":"肉丝炒粉\/面",
        "enName":"Stir-fried Pork Rice Noodles\/Noodle ",
        "price1":13.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/tf/rscm.png",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"RiceCombo",
        "name":"蹄花汤饭",
        "enName":"Pork Elbow Soup Rice Combo",
        "price1":12.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/tf/thtf.png",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"jfc",
        "name":"水煮肉片",
        "enName":"Spicy soup pork",
        "price1":18.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/cai/szrp.png",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"jfc",
        "name":"豆花牛肉",
        "enName":"Spicy soup beef with tofu",
        "price1":22.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/cai/dhnr.png",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"jfc",
        "name":"烧椒牛肉豆腐煲",
        "enName":"Beef tofu with green pepper sauce",
        "price1":18.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/cai/sjnr.png",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"jfc",
        "name":"毛血旺",
        "enName":"Boiled blood curd",
        "price1":20.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/cai/mxw.png",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"jfc",
        "name":"酸菜鱼",
        "enName":"Fish with pickled mustard greens",
        "price1":20.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/cai/scy.png",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"jfc",
        "name":"辣子肉排",
        "enName":"Spicy ribs",
        "price1":18.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":" ",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"jfc",
        "name":"辣子鸡",
        "enName":"Spicy chicken",
        "price1":18.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/cai/lzj.png",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"jfc",
        "name":"辣子鸡脆骨",
        "enName":"Spicy chicken crispy bone",
        "price1":18.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/cai/lzjcg.png",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"jfc",
        "name":"火爆肥肠",
        "enName":"Deep fried spicy intestine",
        "price1":18.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/cai/hbfc.png",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"jfc",
        "name":"火爆腰花",
        "enName":"Fried pork kidney with pickle",
        "price1":18.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/cai/hbyh.png",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"jfc",
        "name":"火爆猪肝",
        "enName":"Fried pork liver with pickle",
        "price1":18.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/cai/pjzg.png",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"jfc",
        "name":"酱爆猪肝",
        "enName":"Fried pork liver with cabbage",
        "price1":18.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/cai/jbzg.png",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"jfc",
        "name":"泡椒鸡杂",
        "enName":"Fried gizzard with spicy pickle pepper",
        "price1":18.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/cai/pjjz.png",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"jfc",
        "name":"泡椒黄喉",
        "enName":"Fried bezoar throat with spicy pickle pepper",
        "price1":20.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/cai/pjhh.png",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"jfc",
        "name":"鲜椒鸡",
        "enName":"Fried chicken with spicy pickle pepper",
        "price1":18.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/cai/xjj.png",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"jfc",
        "name":"鲜椒三脆",
        "enName":"Fried gizzard, bezoar throat and omasum with spicy pickle pepper",
        "price1":18.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/cai/xjsc.png",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"jcc",
        "name":"鱼香肉丝",
        "enName":"Fish-flavored sliced pork",
        "price1":16.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/cai/yxrs.jpg",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"jcc",
        "name":"宫保鸡丁",
        "enName":"Kong-pao Chicken",
        "price1":16.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/cai/gbjd.png",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"jcc",
        "name":"香干回锅肉",
        "enName":"Twice cooked pork with tofu skin ",
        "price1":16.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/cai/xghgr.png",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"jcc",
        "name":"香干小炒肉",
        "enName":"Fried pork with pepper and tofu skin ",
        "price1":16.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/cai/xgxcr.png",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"jcc",
        "name":"锅包肉",
        "enName":"French syrup-style soft-fried pork chop",
        "price1":16.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/cai/gbr.png",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"jcc",
        "name":"椒盐吉士肉排",
        "enName":"Fried Custard Meat Steak",
        "price1":16.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":" ",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"jcc",
        "name":"糖醋松鼠鱼柳",
        "enName":"Sweet and sour squirrel fish",
        "price1":18.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/cai/ssyl.png",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"jcc",
        "name":"麻辣香锅",
        "enName":"Dry hot pot",
        "price1":18.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/cai/mlxg.png",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"jcc",
        "name":"干锅虾",
        "enName":"Dry spicy shrimp",
        "price1":18.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/cai/ggx.png",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"jcc",
        "name":"尖椒香干腊肉",
        "enName":"Fried smoked meat with garlic sprouts",
        "price1":16.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/cai/xglr.png",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"jcc",
        "name":"泡椒肉丝",
        "enName":"Fried sliced meat with pickle pepper",
        "price1":18.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/cai/pjrs.png",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"jcc",
        "name":"泡椒牛肉",
        "enName":"Fried beef with pickle pepper",
        "price1":18.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/cai/pjrs.png",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"jcc",
        "name":"青椒肉丝",
        "enName":"Fried sliced meat with green pepper",
        "price1":16.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/cai/qjrs.png",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"jcc",
        "name":"土豆肉丝",
        "enName":"Fried sliced meat with potato",
        "price1":14.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/cai/tdrs.png",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"jcc",
        "name":"蒜薹肉丝",
        "enName":"Fried sliced meat with garlic sprouts",
        "price1":15.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/cai/strs.png",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"jcc",
        "name":"蒜薹老腊肉",
        "enName":"Fried sliced smoked meat with garlic sprouts",
        "price1":16.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/cai/stlr.png",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"jcc",
        "name":"豉椒牛肉",
        "enName":"Fried beef with bean sauce and green pepper",
        "price1":18.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/cai/cjnr.png",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"jcc",
        "name":"蘑菇牛肉",
        "enName":"Fried beef with mushroom",
        "price1":18.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/cai/mgnr.png",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"jcc",
        "name":"麻婆豆腐",
        "enName":"Mapo tofu",
        "price1":14.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/cai/mpdf.png",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"jcc",
        "name":"红烧肉",
        "enName":"Stewed pork",
        "price1":13.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/cai/hsr.png",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"jcc",
        "name":"香酥鸡",
        "enName":"Crispy fried chicken",
        "price1":15.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/cai/xsj.png",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"jcc",
        "name":"滑蛋虾仁",
        "enName":"Scrambled egg with shrimp",
        "price1":18.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/cai/hdxr.png",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"jcc",
        "name":"鱼香茄子",
        "enName":"Fish-flavored eggplant and meat",
        "price1":15.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/cai/yxqz.png",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"jcc",
        "name":"腊肉花菜",
        "enName":"Cauliflower with smoked meat",
        "price1":16.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/cai/lwhc.png",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"sv",
        "name":"炒上海白",
        "enName":"Fried shanghai vegetable",
        "price1":13.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/cai/cshb.png",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"sv",
        "name":"尖椒豆皮",
        "enName":"Green pepper tofu skin",
        "price1":14.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/cai/jjdp.png",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"sv",
        "name":"油渣莲白",
        "enName":"Cabbage with fried pork",
        "price1":13.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/cai/yzlb.png",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"sv",
        "name":"干煸四季豆",
        "enName":"Dried green bean",
        "price1":14.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/cai/gbsjd.png",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"sv",
        "name":"土豆豆角茄子煲",
        "enName":"Eggplant with Chinese long Bean and potato",
        "price1":14.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/cai/djqzb.png",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"sv",
        "name":"番茄炒蛋",
        "enName":"Tomato and scrambled eggs",
        "price1":14.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/cai/fqcd.png",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"sv",
        "name":"炒土豆丝",
        "enName":"Fried potato floss",
        "price1":12.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/cai/ctds.png",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"sv",
        "name":"蚝油生菜",
        "enName":"Oyster sauce lettuce",
        "price1":14.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/cai/hysc.png",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"Soup",
        "name":"番茄蛋汤",
        "enName":"Tomato and egg Soup",
        "price1":14.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/cai/fqdt.png",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"Soup",
        "name":"蹄花汤",
        "enName":"Trotter soup",
        "price1":16.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/cai/tht.png",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"Soup",
        "name":"小菜酥肉汤",
        "enName":"Fried pork soup with vegetable",
        "price1":14.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/cai/xcsrt.png",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"Soup",
        "name":"小菜豆腐汤",
        "enName":"Tofu soup",
        "price1":13.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/cai/xcdft.png",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"cd",
        "name":"红油鸡片",
        "enName":"Chicken in chili Sauce",
        "price1":15.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/cai/hyjp.jpg",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"cd",
        "name":"手撕鸡",
        "enName":"Shredded chicken",
        "price1":15.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/cai/ssj.png",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"cd",
        "name":"蒜泥白肉",
        "enName":"Meat in garlic chili sauce",
        "price1":15.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/cai/snbr.png",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"yl",
        "name":"可乐",
        "enName":"Pop",
        "price1":2.49,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/yl/cola.png",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"yl",
        "name":"冰红茶",
        "enName":"Ice Tea",
        "price1":2.49,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/yl/icetea.png",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"yl",
        "name":"王老吉",
        "enName":"Canton Cold Tea",
        "price1":2.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/yl/wlj.png",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"yl",
        "name":"大绿茶",
        "enName":"Arizona",
        "price1":2.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/yl/arizona.png",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"yl",
        "name":"菠萝啤",
        "enName":"Pineapple beer",
        "price1":2.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/yl/blp.png",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"yl",
        "name":"椰奶",
        "enName":"Coconut milk",
        "price1":3.49,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/yl/yz.png",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"yl",
        "name":"气泡水",
        "enName":"soda water 2.49",
        "price1":2.49,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/yl/spw.png",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"yl",
        "name":"冰粉",
        "enName":"Chongqing Jelly",
        "price1":3.49,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/yl/bf.jpg",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"side",
        "name":"炸年糕",
        "enName":"Fried Rice Cake",
        "price1":6.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/side/zng.jpg",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"side",
        "name":"狼牙土豆",
        "enName":"Chongqing Fires",
        "price1":5.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/side/lytd.jpg",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"side",
        "name":"香酥鸡腿",
        "enName":"Crispy Fried Chicken Leg",
        "price1":7.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":" ",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"side",
        "name":"酥肉",
        "enName":"Chongqing style Fried Pork",
        "price1":8.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/side/sr.jpg",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"side",
        "name":"炸鸡脆骨",
        "enName":"Fried Chicken Cartilage",
        "price1":10.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/side/zjcg.jpg",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"side",
        "name":"冒青菜",
        "enName":"Hot Pot Vegetable",
        "price1":5.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/side/mqc.jpg",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"side",
        "name":"炸虾卷(4pc）",
        "enName":"Fried Shrimp Spring Roll",
        "price1":7.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/side/zxj.jpg",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"side",
        "name":"炸鲜奶(3pc）",
        "enName":"Fried Lobster Ball",
        "price1":7.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/side/zxn.jpg",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"side",
        "name":"炸豆腐",
        "enName":"Fried Tofu",
        "price1":6.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/side/zdf.jpg",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"side",
        "name":"烧椒鸡皮蛋",
        "enName":"Roasted Peppers with Century Eggs",
        "price1":8.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/side/sjpd.jpg",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"side",
        "name":"炸猪排",
        "enName":"Fried Pork Steak",
        "price1":9.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/side/zzp.jpg",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"side",
        "name":"口水鸡",
        "enName":"Chicken in chili source",
        "price1":9.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/side/ksj.jpg",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"side",
        "name":"蒜泥白肉",
        "enName":"Pork in Spicy Garlic Sauce",
        "price1":9.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/side/snbr.jpg",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"side",
        "name":"芝麻球(6pc）",
        "enName":"Chicken in chili source",
        "price1":7.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/side/zmq.jpg",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"side",
        "name":"红糖糍粑(5pc)",
        "enName":"Fried Rice Cake with black sugar",
        "price1":8.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/side/htcb.jpg",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"side",
        "name":"烤苕皮",
        "enName":"BBQ Potato Skin",
        "price1":4.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/side/ksp.jpg",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"fh",
        "name":"综合冒菜",
        "enName":"Quick Hot Pot",
        "price1":18.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/side/zhmc.jpg",
        "desc1":"含毛肚，黄喉，丸子，猪肉片，猪血，豆皮，土豆片，白菜等蔬菜 Include: triple, meat ball, meat, tofu skin, potato",
        "desc2":" "
    },
    {
        "categoryId":"fh",
        "name":"牛肉冒菜",
        "enName":"Quick Beef Hot Pot",
        "price1":20.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/side/nrmc.jpg",
        "desc1":"含牛肉，毛肚，黄喉，丸子，猪血，豆皮，土豆片，白菜等蔬菜 Include: triple, meat ball, meat, tofu skin, potato",
        "desc2":" "
    },
    {
        "categoryId":"fh",
        "name":"冒土豆片",
        "enName":"Hot Pot Potato Chips",
        "price1":6.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/side/mtdp.jpg",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"fh",
        "name":"冒香菜牛肉",
        "enName":"Hot Pot Beef with Coriander",
        "price1":14.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/side/mxcnr.jpg",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"fh",
        "name":"冒豆皮",
        "enName":"Hot Pot Tofu Skin",
        "price1":8.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/side/mdp.jpg",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"fh",
        "name":"冒藕片",
        "enName":"Hot Pot Lotus Root",
        "price1":7.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/side/mop.jpg",
        "desc1":" ",
        "desc2":" "
    },
    {
        "categoryId":"fh",
        "name":"麻酱涮牛肚",
        "enName":"Triple in Chili Sesame Sauce ",
        "price1":14.99,
        "size1":" ",
        "price2":" ",
        "size2":" ",
        "image":"./pic/res_project/side/snd.jpg",
        "desc1":" ",
        "desc2":" "
    }
]
}